---
- hosts: all
  become: yes
  gather_facts: no
  vars:
    ansible_user: "cumulus"
    ansible_ssh_pass: "CumulusLinux!"
    ansible_become_pass: "CumulusLinux!"
    private_ssh_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  tasks:
  - name: Create automation User Account
    user: 
      name: automation
      groups: sudo
      shell: /bin/bash
    become: true

  - name: Install Pre-Shared SSH Key in new automation account
    authorized_key:
      user: automation
      state: present
      key: "{{ private_ssh_key }}"
    become: true
