- hosts: leaf
  become: yes
  become_method: sudo
  vars:
    devices:
        leaf01:
            clag_role: "primary"
            clag_mac: "44:38:39:FF:00:01"
            clag_backupip: "192.168.0.12"
            loopback: "10.255.255.1/32"
            bgpasn: "65101"
            VLANS:
                - vlan: "10"
                  vrrip: "10.0.10.1/24"
                  vrrmac: "00:00:00:00:1a:10"
                  bond: "SERVER01"
                  interface: "swp1"
                  realip: "10.0.10.2/24"
                - vlan: "20"
                  vrrip: "10.0.20.1/24"
                  vrrmac: "00:00:00:00:1a:20"
                  bond: "SERVER02"
                  interface: "swp2"
                  realip: "10.0.20.2/24"
        leaf01:
            clag_role: "secondary"
            clag_mac: "44:38:39:FF:00:01"
            clag_backupip: "192.168.0.11"
            loopback: "10.255.255.2/32"
            bgpasn: "65102"
            VLANS:
                - vlan: "10"
                  vrrip: "10.0.10.1/24"
                  vrrmac: "00:00:00:00:1a:10"
                  bond: "SERVER01"
                  interface: "swp1"
                  realip: "10.0.10.3/24"
                - vlan: "20"
                  vrrip: "10.0.20.1/24"
                  vrrmac: "00:00:00:00:1a:20"
                  bond: "SERVER02"
                  interface: "swp2"
                  realip: "10.0.20.3/24"


  tasks:
  - name: Deploy interface configuration
    nclu:
        commit: false
        description: "Deploy interface configuration"
        commands:
            - add clag peer sys-mac {{ devices[ansible_hostname].clag_mac }} interfaces swp49-50 primary backup-ip {{ devices[ansible_hostname].clag_backupip }}
            - add clag port bond {{ devices[ansible_hostname].VLANS[0].bond}} interface {{ devices[ansible_hostname].VLANS[0].interface }} clag-id 1
            - add clag port bond {{ devices[ansible_hostname].VLANS[1].bond}} interface {{ devices[ansible_hostname].VLANS[1].interface }} clag-id 2
            - add bond {{ devices[ansible_hostname].VLANS[0].bond }} bridge access  {{ devices[ansible_hostname].VLANS[0].vlan }}
            - add bond {{ devices[ansible_hostname].VLANS[1].bond }} bridge access  {{ devices[ansible_hostname].VLANS[1].vlan }}
            - add vlan {{ devices[ansible_hostname].VLANS[0].vlan }} ip address {{ devices[ansible_hostname].VLANS[0].realip }}
            - add vlan {{ devices[ansible_hostname].VLANS[1].vlan }} ip address {{ devices[ansible_hostname].VLANS[1].realip }}
            - add vlan {{ devices[ansible_hostname].VLANS[0].vlan }} ip address-virtual {{ devices[ansible_hostname].VLANS[0].realip }}
            - add vlan {{ devices[ansible_hostname].VLANS[1].vlan }} ip address-virtual {{ devices[ansible_hostname].VLANS[1].realip }}
            - add loopback lo {{ devices[ansible_hostname].loopback }}
            - add bgp autonomous-system {{ devices[ansible_hostname].bgpasn }}
            - add bgp neighbor swp51 remote-as external
            - add bgp neighbor swp52 remote-as external
            - add bgp network {{ devices[ansible_hostname].loopback }}
            - add bgp network {{ devices[ansible_hostname].VLANS[0].vrrip }}
            - add bgp network {{ devices[ansible_hostname].VLANS[0].vrrip }}
