---
- name: Lab 2--Installing NetQ on Switches
  hosts: leaf:spine
  remote_user: cumulus
  become: yes
  tasks:
    - name: Install NetQ Repo Source
      copy:
        content: |
          deb http://apps3.cumulusnetworks.com/repos/deb CumulusLinux-3 netq-1.1
        dest: /etc/apt/sources.list.d/cumulus-apps.list

    - name: Install Cumulus NetQ
      apt: name=cumulus-netq update_cache=yes state=latest

    - name: Add Mgmt VRF
      nclu: 
        commands:
        - add vrf mgmt
        commit: true
        description: "Lab 2: Installing Netq"

    - name: Copy Netq Configuration File
      copy: src=netq.yml.switch dest=/etc/netq/netq.yml

    - name: Copy NTP Config File
      copy: src=ntp.conf dest=/etc/ntp.conf

    - name: Stop Existing Netq Daemons (netqd and netq-agent)
      service: name={{item}} state=stopped enabled=no
      with_items:
      - "netq-agent"
      - "netqd"
      - "ntp"

    - name: Start Netq Daemons in MGMT VRF (netqd@mgmt and netq-agent@mgmt)
      service: name={{item}} state=restarted enabled=yes
      with_items:
      - "netq-agent@mgmt"
      - "netqd@mgmt"
      - "ntp@mgmt"
    
- name: Lab 2--Installing NetQ on Servers
  hosts: server
  remote_user: cumulus
  become: yes
  tasks:
    - name: Install NetQ Repo Key
      shell: wget -O- https://apps3.cumulusnetworks.com/setup/cumulus-apps-deb.pubkey | apt-key add -

    - name: Install NetQ Repo Source
      copy: 
        content: |
          deb [arch=amd64] https://apps3.cumulusnetworks.com/repos/deb xenial netq-1.1
        dest: /etc/apt/sources.list.d/cumulus-apps-deb-xenial.list


    - name: Install Cumulus NetQ
      apt: name=cumulus-netq update_cache=yes state=latest

    - name: Copy NetQ Config File
      copy: src=netq.yml.server dest=/etc/netq/netq.yml

    - name: Copy NTP Config File
      copy: src=ntp.conf dest=/etc/ntp.conf

    - name: Set UTC Timezone
      copy: 
        content: |
          Etc/UTC
        dest: /etc/timezone

    - name: Apply Timezone Now
      shell: dpkg-reconfigure -f noninteractive tzdata

    - name: Restart Netq Daemons (netqd and netq-agent and ntp)
      service: name={{item}} state=restarted enabled=yes
      with_items:
      - "rsyslog"
      - "netq-agent"
      - "netqd"
      - "ntp"

