- hosts: all         # Run this against all Hosts in the ansible inventory file
  remote_user: cumulus
  become: yes
  become_method: sudo
  gather_facts: no   # Don't query the remote node for any identifying information before running tasks
  tasks:             # All of these tasks are executed on the remote device
    - name: Make a ".ssh" Directory for the Cumulus user
      file: path=/home/cumulus/.ssh state=directory mode=0755

    - name: Copy our Authorized Key to the Cumulus user
      copy: src=/home/cumulus/.ssh/id_rsa.pub dest=/home/cumulus/.ssh/authorized_keys

    - name: Enable passwordless sudo for the Cumulus User
    - lineinfile: "dest=/etc/sudoers.d/10_cumulus state=present line='cumulus ALL=(ALL) NOPASSWD:ALL'"
