---
- hosts: all
  remote_user: cumulus
  become: yes
  become_method: sudo
  gather_facts: no
  tasks:
  - name: write the networking config file
    copy: src=interface_default.txt dest=/etc/network/interfaces

  - name: restart networking
    shell: ifreload -a
